### ISSUE TITLE
GLTF model to check after PBR + animation integration

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#628]
Hello @xtanion ,
While importing various models I was facing the below issues

1. After importing the models they aren't clearly visible as you can see below (I don't know whether it is related to importing or light or something else)

    1. BoomBox:
![BoomBox](https://user-images.githubusercontent.com/64432063/177738245-76819982-4cc8-41d0-8c4d-74999c32047e.gif)

    1. BarramundiFish:
![BarramundiFish](https://user-images.githubusercontent.com/64432063/177738303-abb273f9-7d6d-41ab-a8b0-c0a13456ab5f.gif)

1. Unicode❤♻Test:
It seems `pygltflib` is unable to decode the Unicode characters
```python
Traceback (most recent call last):
  File "d:\FuryWorkspace\fury\docs\tutorials\01_introductory\viz_gltf.py", line 28, in <module>
    gltf_obj = glTF(filename, apply_normals=True)
    self.gltf = GLTF2().load(filename)
  File "D:\FuryWorkspace\fury-env\lib\site-packages\pygltflib\__init__.py", line 1102, in load
    obj = cls.load_json(fname)
  File "D:\FuryWorkspace\fury-env\lib\site-packages\pygltflib\__init__.py", line 1050, in load_json
    obj = cls.gltf_from_json(f.read())
  File "C:\Users\ganim\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 285: character maps to <undefined>
```

1. Fox:
`glTF` type doesn't display any model
![image](https://user-images.githubusercontent.com/64432063/177741598-90adaa0c-5a18-41c1-bf8f-a45057887e0b.png)
Do we support the `.glb` file??
Because when I try to import `Fox` in `glTF-Binary`  tmode it throws the below error
```python
Traceback (most recent call last):
  File "d:\FuryWorkspace\fury\docs\tutorials\01_introductory\viz_gltf.py", line 28, in <module>
    gltf_obj = glTF(filename, apply_normals=True)
  File "gltf.py", line 49, in __init__
    self.inspect_scene(0)
  File "gltf.py", line 82, in inspect_scene
    self.transverse_node(node_id, self.init_transform)
  File "gltf.py", line 120, in transverse_node
    self.load_mesh(mesh_id, next_matrix)
  File "gltf.py", line 146, in load_mesh
    vertices = self.get_acc_data(attributes.POSITION)
  File "gltf.py", line 209, in get_acc_data
    return self.get_buff_array(buff_id, d_type['dtype'], byte_length,
  File "gltf.py", line 247, in get_buff_array
    if uri.startswith('data:application/octet-stream;base64') or \
AttributeError: 'NoneType' object has no attribute 'startswith'
```
the `uri` is None. Yes, It is correct because the `.glb` file doesn't have any separate bin files for the buffer.

Also if we don't provide any mode to `read_viz_gltf`, the `glTF` mode isn't selected as the default.
This is because of [this line](https://github.com/fury-gl/fury/blob/master/fury/data/fetcher.py#L703) in `fetcher.py` where you are choosing the last type, so considering file order `glTF` will always be at the top (in windows as per I know) than the other  `glTF-*` type files.

I will continue to import another type of models too and let you know if I found something.

_Originally posted by @ganimtron-10 in https://github.com/fury-gl/fury/issues/600#issuecomment-1177331239_

**Comment by chisarie** [comment]
Hello! It seems that this issue is caused by missing lights. Is there any plans to add lighting to the current Fury API? 
One could take inspiration from the API structure of the pyrender project: https://pyrender.readthedocs.io/en/latest/api/index.html#lighting

**Comment by skoudoro** [comment]
Hi @chisarie,

Yes, we plan to add different lighting but by default, there is a light so that why the result is strange.
