### ISSUE TITLE
Bug No module named 'fury.stream.server.FuryVideoFrame'

### ISSUE THREAD

**Issue by SEVENBAY** [fury-gl/fury#921]
after pip install fury, then show bugs bellow:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data1/infer_code/RealTime_HumanEngine_VisualChat/apis/__main__.py", line 3, in <module>
    from apis.api import bp
  File "/data1/infer_code/RealTime_HumanEngine_VisualChat/apis/api.py", line 4, in <module>
    from apis.services import get_turn_config_serv, get_turn_offer_serv, render_serv, index_serv
  File "/data1/infer_code/RealTime_HumanEngine_VisualChat/apis/services.py", line 5, in <module>
    from server.stream.worker import DigitalHumanStreamWorker
  File "/data1/infer_code/RealTime_HumanEngine_VisualChat/server/stream/worker.py", line 19, in <module>
    from fury.stream.server.FuryVideoFrame import FuryVideoFrame
ModuleNotFoundError: No module named 'fury.stream.server.FuryVideoFrame'

**Comment by skoudoro** [comment]
Hi @SEVENBAY,

Do you have cython installed ?

When I look at the code here: https://github.com/fury-gl/fury/blob/8a5bbeb097dda172b6ea8a237d2f6dfd47d33614/fury/stream/server/main.py#L36

this module is a `pyx` so not available if it is not compiled. Did you have access before? if yes, I suppose you compiled this optional module. Can you tell us more?

**Comment by skoudoro** [comment]
I suppose @devmessias can tell you more about this

**Comment by SEVENBAY** [comment]
> Hi @SEVENBAY,
> 
> Do you have cython installed ?
> 
> When I look at the code here:
> 
> https://github.com/fury-gl/fury/blob/8a5bbeb097dda172b6ea8a237d2f6dfd47d33614/fury/stream/server/main.py#L36
> 
> this module is a `pyx` so not available if it is not compiled. Did you have access before? if yes, I suppose you compiled this optional module. Can you tell us more?

hello, I previously installed version 0.10.0 and did not encounter this error. However, today when I installed the environment using the latest version, I encountered this error. I have now specified the installation of version 0.10.0 and it is fine. I am not sure if there is any problem with this latest package

**Comment by skoudoro** [comment]
ok, I think I found the issue. you need to install `av` package : `pip install av`

Then it should as expected for the import ` from fury.stream.server.FuryVideoFrame import FuryVideoFrame `

**Comment by skoudoro** [comment]
Please let us know if it is ok then we can close the issue

**Comment by skoudoro** [comment]
Closing `pip install av` should fix the issue
