### ISSUE TITLE
DOC warnings and other QoL improvements

### ISSUE THREAD

**Issue by robinroy03** [fury-gl/fury#940]
- Numpy 2.0 migration bugs are still present on tutorials
- When developing the library using fury-dev version, the @warn_on_args_to_kwargs() won't get triggered so some warns can go unnoticed.
- Warns should mention line numbers if possible, for easy debugging.

**Comment by skoudoro** [comment]
Can you look at point 2 and 3 @WassCodeur? 

Thank you

**Comment by WassCodeur** [comment]
> Can you look at point 2 and 3 @WassCodeur?
> 
> Thank you

Hi @skoudoro, @robinroy03  ,

Alright,  well noted

**Comment by Prtm2110** [comment]
Hello, I would like to work in these 
> * Numpy 2.0 migration bugs are still present on tutorials

Could you please specify where or ref to the failing checks?

> * Warns should mention line numbers if possible, for easy debugging.

```python
from fury.decorators import warn_on_args_to_kwargs
import fury
@warn_on_args_to_kwargs()
def f(a, b, *, c, d=1, e=1):
    return a + b + c + d + e

f(1, 2, 3, 4, 5)

f(1, 2, c=3, d=4, e=5)

f(1, 2, 2, 4, e=5)

f(1, 2, c=3, d=4)

f(1, 2, d=3, e=5)
```
Below here 15 is the line number or I am interpreting the issue incorrectly?
```
(fury) xoein@xoeinXD:~/Desktop/FuriousSpace$ python3 /home/xoein/Desktop/FuriousSpace/scratchpad/warnn.py
Traceback (most recent call last):
  File "/home/xoein/Desktop/FuriousSpace/fury/fury/decorators.py", line 158, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: f() missing 1 required keyword-only argument: 'c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xoein/Desktop/FuriousSpace/scratchpad/warnn.py", line 15, in <module>
    f(1, 2, d=3, e=5)
  File "/home/xoein/Desktop/FuriousSpace/fury/fury/decorators.py", line 176, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: f() missing 1 required keyword-only argument: 'c'
```

**Comment by uuu4** [comment]
> * When developing the library using fury-dev version, the @warn_on_args_to_kwargs() won't get triggered so some warns can go unnoticed.

Hi, can i work on this?

**Comment by robinroy03** [comment]
hi @Prtm2110 are you still working on this?

**Comment by Prtm2110** [comment]
Hello, yes I was working on it, but @uuu4 go ahead on this! My suggestion would be is to write a python script to execute all gallery example one by one and check there results.

**Comment by Krishna-web-hub** [comment]
Hi @robinroy03 , I have checked all the example by running a python script everything is running fine and also the warn `@warn_on_args_to_kwargs()` is also fixed .please check it out.

**Comment by passionworkeer** [comment]
针对 Numpy 2.0 迁移问题，可以在 CI 中添加 matrix 测试（numpy<2.0 和 numpy>=2.0）来捕获兼容性警告。对于 @warn_on_args_to_kwargs() 在 dev 版本不触发的问题，可以考虑将其改为在调试模式（FURY_DEBUG=1）下强制启用，而非依赖版本检测。添加行号信息可以借助 Python 的 warnings.warn() 默认行为，或使用 warnings.formatwarning 自定义格式。

**Comment by Krishna-web-hub** [comment]
Hi @passionworkeer , i have checked for numpy<2.0 all the examples are running successfully. Beside the Pr was attached to fix the issue.
